export const SET_PORTAL_ORDER = 'SET_PORTAL_ORDER';
export const SET_PORTAL_INGREDIENT = 'SET_PORTAL_INGREDIENT';
export const SET_PORTAL_API = 'SET_PORTAL_API';
export const RESET_PORTAL = 'RESET_PORTAL';
